### ISSUE TITLE
Rigid bodies limitation

### ISSUE THREAD

**Issue by Ehsanizadi** [GPUSPH/gpusph#11]
Hi all,
I am using GPUSPH for a few weeks for my simulation project. Its really great, thanks indeed for making it opensource.

My research is about the dynamic beahviour of rigid bodies when they hit fluids with different viscosities. For modelling of rigid bodies, I see that only Cube, Sphere and Cylinder shapes are available and not Cone shape. I am aware this is not inherently a limitation in GPUSPH, but in ODE engine. (and unluckily I need to use Cone shape!)

My question is that is that possible to make an arbitrary-shaped geometry (using Crixus) and use it as a rigid body in GPUSPH? And for undertaking ODE to take care of that object, setting a collision shape made of Trimesh.
If such option is not available yet, could it be considered as an enhancements for next releases of GPUSPH?

**Comment by Narcolessico** [comment]
Hello Ehsan,

thank you for the feedback. A generic shape class is almost ready: it is called `STLMesh` since it loads an arbitrary mesh from a STL file, then it places a boundary particle in each vertex. It supports rigid body dynamics and collisions, all through ODE. So all you need is a little more patience ;)

If you want to implement it by yourself, you could extend the Cone class and set the inertia by yourself (dMass.I). Be careful with the center of mass, ODE handles it in a weird way sometimes. If you also need collisions, then you need  a ODE Trimesh. ODE can compute the object inertia automatically from the mesh, but assumes it has a homogeneous density.

Crixus is mostly useful to preprocess scenarios you want to simulate with `SA_BOUNDARY`. It could be a nice workaround to use it instead of the `STLMesh` class, but you would still have to set the inertia matrix manually in ODE. If you are using LJ boundaries, then the standard `Cone::Fill()` will suffice.

**Comment by Ehsanizadi** [comment]
Thank you very much for the hints.
Well, I try to extend the Cone class myself until the new GPUSPH releases. 
I hope it to be released soon!
