### ISSUE TITLE
How do handle 3rd party contributions?

### ISSUE THREAD

**Issue by sanguinariojoe** [GPUSPH/gpusph#31]
Related with https://github.com/GPUSPH/gpusph/issues/29 and https://github.com/GPUSPH/gpusph/issues/30

How do you handle 3rd party contributions? I mean, let's say I have something superb to merge in your code (which is not the case yet)... May I create a Pull Request (PR) here, in github? Are you then managing that manually?

I strongly suggest you to forgive about the private repository, using github as the upstream one, keeping as minimum as possible owners/contributors, in such a way the development process is based in forks and PRs. This have a number of benefits (in fact is the standard nowadays). The most remarkably ones are:

* Simplified relation with the community, including both, the users and devs
* Significant reduction of management efforts, since just github infrastructure shall be maintained, which also have a lot of awesome features
* Unit testing can be easily implemented
* Wiki can be handled as a git repo as well (some tasks can be even automatized)
* Better and more accurate stats

**Comment by agnesLeroy** [comment]
Hi!
This is interesting indeed, we need to think about it. Thank you for the advice.
Cheers,
Agnès

**Comment by Oblomov** [comment]
Hello @sanguinariojoe 

We're looking forward to more participation from users and developers interested in GPUSPH. We have now made the `next` branch public. This is the main development branch, on top of which all our development is happening, and on top of which contributions from other parties should also be designed. This effectively enables the “standard GitHub style” fork/PR collaboration model, although using the `next` branch as reference rather than `master` (which for us represents the current released version). This is clarified in the new CONTRIBUTING document in the repository root.

Hopefully this resolves the issue, feel free to reopen if you believe further discussion is needed.

**Comment by sanguinariojoe** [comment]
Forking time! :-)
