### ISSUE TITLE
addXYZFile Trouble

### ISSUE THREAD

**Issue by kyletreece** [GPUSPH/gpusph#46]
Hello,

I am attempting to modify the provided CompleteSaExample problem to use the addXYZFile method, instead of the addHDF5File method, for adding semi-analytical boundaries to a problem. I created three XYZ files (just representing point clouds of x,y,z coordinates, no file extensions) from the provided hdfsph files for the example (ignoring the floating body cube at this time) and am able to upload them in the simulation for the t=0 timestep. However, within a few timesteps the fluid particles jump to high velocities and move rapidly up and out of bounds of the simulation (at least this is what it seems like).

If I comment out the fluid particles and only leave the inlet and container then no fluid particles get added, and nothing happens with the simulation. It runs fine, but nothing changes between each timestep.

Is there any documentation on using the addXYZFile method, or do you have any advice or directions you could provide me to help me get it working? If there is a different, preferred space to discuss topics like this please let me know and I will gladly move there.

Thank you!

**Comment by agnesLeroy** [comment]
Hi there,

Regarding your question, I think first you should consider the difference between SA boundaries and particle-type boundaries: with SA boundaries, the SPH interpolation is modified so as to take the truncation of the kernel support close to the walls. This correction implies the calculation of the integral of the kernel on the truncated support. To perform the **exact** calculation of this integral (an approximate calculation is not enough to prevent particle leakage), the formulation proposed by Ferrand et al. (JCP, 2013) uses a mesh of the boundary (triangles in 3D). This implies that a simulation with SA boundaries comprises:
- FLUID particles
- VERTEX particles, which are located at the triangles' tips and move at the wall's velocity
- BOUNDARY_ELEMENTS, i.e. the triangles, but also their normals values and the connectivity information (i.e. which vertices belong to a given BOUDNARY_ELEMENT).

How are you going to recover this information from an XYZ file? This is why in the first place we used a different format, namely the H5SPH format based on HDF5.

Cheers,
Agnès

**Comment by ThinkSolidification** [comment]
Thank you @agnesLeroy for your reply, I am struggling with the same issue, I wonder then why this function is available in the code? Also, do you mind sharing a step by step on how to generate the HDF5 files for the complete SA example shipped with the code?
Best,
Salem

**Comment by kyletreece** [comment]
Hi @agnesLeroy ,

Thank you for your response, that makes a lot of sense regarding the additional information required for SA boundaries.

I have also attempted to use the SALOME + CRIXUS approach for generation of HDF5 files and have had issue with setting up an inlet; I am however able to generate a container and fluid particles. I think I could address the problems I am experiencing if I could reference the .ini file and the full set of .STL files used for the CompleteSaExample, is there any way you can provide these files to me? It would be greatly appreciated.

Thank you!

**Comment by agnesLeroy** [comment]
Hello,

For your information the h5sph files for CompleteSaExample are available for Download on the GPUSPH website. If you want to reconstruct them anyway, you can check the user documentation on the website, that should indicate to you how to proceed. The main thing you should be aware of is that the inlet should be a separate STL file but should also be included in the main geometry.

Cheers,
Agnès

**Comment by agnesLeroy** [comment]
Hi,

This case was a very simplifed version of a ship lock actually. This is why the inlet is done in this way. But it could also be a part of the main container wall instead. What you need to be very careful with is the quality of the mesh, especially on the inlet boundary. You need to have very homogeneous triangles. To set the particle size in GPUSPH, use the result of the testTriangle script (this is explained in the user documentation, take the max. triangle size).

Here comes a zipped file with a set of STL files + ini file for Crixus.
[complete_sa_example.zip](https://github.com/GPUSPH/gpusph/files/2755527/complete_sa_example.zip)


Cheers,
Agnès

**Comment by kyletreece** [comment]
Thank you so much! I will experiment more with the mesh setup and review these new files. I really appreciate your responses and your help on everything!

**Comment by ManuelFalcone** [comment]
Hi @agnesLeroy,

I am trying to use Salome + Crixus for the preprocessing of a GPUSPH simulation of the coolant flow in a drill bit using SA boundaries. I have one inlet, one outlet and then walls. As you suggested in the previous posts, I created an STL file including the mesh of whole geometry and then two other STLs with only the submeshes corresponding to the inlet and outlet, respectively. By using an .ini file analogous to that one you included in the zipped file, I then generated the initial sets of particles for GPUSPH. However, when I then execute the application, the simulation fails almost immediately and throws the following error:

Numbodies : 0
Numforcesbodies : 0
numOpenBoundaries : 2
  allocated 125.4 MiB on host for 913,108 particles (760,922 active)
Copying the particles to shared arrays...
---
Fixing connectivity...FATAL: connectivity: particle id 588053 index 588053 loaded from HDF5 points to non-existing vertices (506361,506412,506404)!

It seems that the cause of the problem lies in the files generated by Crixus. However, I cannot understand why this happens. The 
only things that comes to my mind is that I get the following warning message when I export the mesh in Salome:

“During export mesh with name “Mesh_1” to STL Edges will be missed.
Do you want to continue?

In order to move on with the exporting, I have to press yes. Could this be the cause of the problem? Does Crixus need the edges in order to properly work? Should I use then another mesher instead of Salome? Or does the problem lie somewhere else?

Thank you very much for your help.

Regards

Manuel
