### ISSUE TITLE
About the gpu-architecture

### ISSUE THREAD

**Issue by chenxin202** [GPUSPH/gpusph#72]
Dear developers,
@Oblomov :
I tried to build and test GPUSPH. And it said “[CU] Dambreak3D.onvcc fatal : Value ' sm_86' is not defined for option 'gpu-architecture”. Could you give me some suggestions and how should I deal with it?
Thank you!

**Comment by Oblomov** [comment]
It looks like your CUDA toolkit is too old for the GPU architecture of the device you have.  If I remember correctly, support for 8.6 was introduced in CUDA 11.1, you probabl have an older version of CUDA. You can try forcing the architecture to the highest supported by your CUDA toolkit (e.g. with `make compute=80` or `make compute=75` depending on your CUDA toolkit version), but the right way to fix this issue is to just upgrade your CUDA toolkit.

**Comment by chenxin202** [comment]
Thanks! 
Kind regards
